/*
 
public class Pneumatics extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static Compressor compressor = RobotMap.pneumaticsCompressor;
    static DoubleSolenoid solenoid = RobotMap.solenoid;
    static DoubleSolenoid shifters = RobotMap.shifters;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static boolean running;
    
    public static void init(){
        compressor.start();
    }
    
    public static void moveUp(){
        solenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public static void moveDown(){
        solenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public static void solenoidOff(){
        solenoid.set(DoubleSolenoid.Value.kOff);
    }
    
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        setDefaultCommand(new SolenoidDefault());
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
*/