// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4143.FrisbeeBot.subsystems;
import org.usfirst.frc4143.FrisbeeBot.RobotMap;
import org.usfirst.frc4143.FrisbeeBot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Pneumatics extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static Compressor compressor = RobotMap.pneumaticsCompressor;
    static DoubleSolenoid solenoid = RobotMap.solenoid;
    static DoubleSolenoid shifters = RobotMap.shifters;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static boolean running;
    
    public static void init(){
        compressor.start();
    }
    
    public static void moveUp(){
        solenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public static void moveDown(){
        solenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public static void solenoidOff(){
        solenoid.set(DoubleSolenoid.Value.kOff);
    }
    
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        setDefaultCommand(new SolenoidDefault());
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}